logging:
  level:
    org.springframework.security: INFO
    
example:
  user: William
  
---
spring:
  profiles: prd

info:
  description: prd env  
  
---
spring:
  profiles: dev

info:
  description: dev env  